[[constraint]]
  name = "github.com/pulumi/pulumi"
  source = "github.com/Frassle/pulumi"
  branch = "dotnet"

# Redirect all Terraform references to our fork.
[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"
